language: cpp
env:
  matrix:
  - COMPILER=g++-4.8
  - COMPILER=g++-4.9
  - COMPILER=g++-5
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
    - g++-4.9
    - g++-5
script:
  make CXX=$COMPILER -j2
